//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free.Core.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Free.Core.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a boolean value in a list of booleans..
        /// </summary>
        internal static string BoolInListDescription {
            get {
                return ResourceManager.GetString("BoolInListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a boolean value in a Parameters..
        /// </summary>
        internal static string BoolInParametersDescription {
            get {
                return ResourceManager.GetString("BoolInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of boolean values in a Parameters..
        /// </summary>
        internal static string BoolListInParametersDescription {
            get {
                return ResourceManager.GetString("BoolListInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an array of bytes in a Parameters..
        /// </summary>
        internal static string ByteArrayInParametersDescription {
            get {
                return ResourceManager.GetString("ByteArrayInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a byte in an array..
        /// </summary>
        internal static string ByteInArrayDescription {
            get {
                return ResourceManager.GetString("ByteInArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a floating-point value in a Parameters..
        /// </summary>
        internal static string DoubleInParametersDescription {
            get {
                return ResourceManager.GetString("DoubleInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of  floating-point values in a Parameters..
        /// </summary>
        internal static string DoubleListInParametersDescription {
            get {
                return ResourceManager.GetString("DoubleListInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Count={0}).
        /// </summary>
        internal static string FormatCountInParentheses {
            get {
                return ResourceManager.GetString("FormatCountInParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string FormatListConverterIndexInParenthese {
            get {
                return ResourceManager.GetString("FormatListConverterIndexInParenthese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} propertie&amp;s:.
        /// </summary>
        internal static string FormatListEditorFormsPropertiesLabelWithText {
            get {
                return ResourceManager.GetString("FormatListEditorFormsPropertiesLabelWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string FormatStringInDoublequotes {
            get {
                return ResourceManager.GetString("FormatStringInDoublequotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ListEditorFormPropertyGridValueNameText {
            get {
                return ResourceManager.GetString("ListEditorFormPropertyGridValueNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propertie&amp;s:.
        /// </summary>
        internal static string ListEditorFormsPropertiesLabelWithoutText {
            get {
                return ResourceManager.GetString("ListEditorFormsPropertiesLabelWithoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point Number List Editor.
        /// </summary>
        internal static string ListOfDoubleEditorCaption {
            get {
                return ResourceManager.GetString("ListOfDoubleEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point Number.
        /// </summary>
        internal static string ListOfDoubleEditorGridValueTypeText {
            get {
                return ResourceManager.GetString("ListOfDoubleEditorGridValueTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit Integer Number List Editor.
        /// </summary>
        internal static string ListOfLongEditorCaption {
            get {
                return ResourceManager.GetString("ListOfLongEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit Integer Number.
        /// </summary>
        internal static string ListOfLongEditorGridValueTypeText {
            get {
                return ResourceManager.GetString("ListOfLongEditorGridValueTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters List Editor.
        /// </summary>
        internal static string ListOfParametersEditorCaption {
            get {
                return ResourceManager.GetString("ListOfParametersEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ListOfParametersEditorGridValueTypeText {
            get {
                return ResourceManager.GetString("ListOfParametersEditorGridValueTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String List Editor.
        /// </summary>
        internal static string ListOfStringEditorCaption {
            get {
                return ResourceManager.GetString("ListOfStringEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string ListOfStringEditorGridValueTypeText {
            get {
                return ResourceManager.GetString("ListOfStringEditorGridValueTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a 64-bit integer value in a Parameters..
        /// </summary>
        internal static string LongInParametersDescription {
            get {
                return ResourceManager.GetString("LongInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of 64-bit integer values in a Parameters..
        /// </summary>
        internal static string LongListInParametersDescription {
            get {
                return ResourceManager.GetString("LongListInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a number in a list of numbers..
        /// </summary>
        internal static string NumberInListDescription {
            get {
                return ResourceManager.GetString("NumberInListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss of data!.
        /// </summary>
        internal static string ParameterEditorFormListConversionLossOfDataWarningMessageBoxCaption {
            get {
                return ResourceManager.GetString("ParameterEditorFormListConversionLossOfDataWarningMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List contains more than one element. All elements but the first will be lost in conversion of the type.
        ///
        ///Continue anyway?.
        /// </summary>
        internal static string ParameterEditorFormListConversionLossOfDataWarningMessageBoxText {
            get {
                return ResourceManager.GetString("ParameterEditorFormListConversionLossOfDataWarningMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean.
        /// </summary>
        internal static string ParametersEditorFormBoolDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormBoolDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string ParametersEditorFormBoolDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormBoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to booleans.
        /// </summary>
        internal static string ParametersEditorFormBoolListDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormBoolListDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of booleans.
        /// </summary>
        internal static string ParametersEditorFormBoolListDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormBoolListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string ParametersEditorFormByteArrayDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormByteArrayDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of bytes.
        /// </summary>
        internal static string ParametersEditorFormByteArrayDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormByteArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floatingpointnumber.
        /// </summary>
        internal static string ParametersEditorFormDoubleDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormDoubleDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point number.
        /// </summary>
        internal static string ParametersEditorFormDoubleDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormDoubleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floatingpointnumbers.
        /// </summary>
        internal static string ParametersEditorFormDoubleListDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormDoubleListDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of floating-point numbers.
        /// </summary>
        internal static string ParametersEditorFormDoubleListDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormDoubleListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integernumber.
        /// </summary>
        internal static string ParametersEditorFormLongDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormLongDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit integer number.
        /// </summary>
        internal static string ParametersEditorFormLongDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integernumbers.
        /// </summary>
        internal static string ParametersEditorFormLongListDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormLongListDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of 64-bit integer numbers.
        /// </summary>
        internal static string ParametersEditorFormLongListDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormLongListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already used!.
        /// </summary>
        internal static string ParametersEditorFormNameInUseErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("ParametersEditorFormNameInUseErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with same name already exists in Parameters..
        /// </summary>
        internal static string ParametersEditorFormNameInUseErrorMessageBoxText {
            get {
                return ResourceManager.GetString("ParametersEditorFormNameInUseErrorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string ParametersEditorFormParametersDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormParametersDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ParametersEditorFormParametersDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listofParameters.
        /// </summary>
        internal static string ParametersEditorFormParametersListDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormParametersListDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Parameters.
        /// </summary>
        internal static string ParametersEditorFormParametersListDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormParametersListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string ParametersEditorFormStringDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormStringDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string ParametersEditorFormStringDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strings.
        /// </summary>
        internal static string ParametersEditorFormStringListDefaultName {
            get {
                return ResourceManager.GetString("ParametersEditorFormStringListDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of strings.
        /// </summary>
        internal static string ParametersEditorFormStringListDescription {
            get {
                return ResourceManager.GetString("ParametersEditorFormStringListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Parameters value in a list of Parameters..
        /// </summary>
        internal static string ParametersInListDescription {
            get {
                return ResourceManager.GetString("ParametersInListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Parameters value in a Parameters..
        /// </summary>
        internal static string ParametersInParametersDescription {
            get {
                return ResourceManager.GetString("ParametersInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of Parameters values in a Parameters..
        /// </summary>
        internal static string ParametersListInParametersDescription {
            get {
                return ResourceManager.GetString("ParametersListInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortDown {
            get {
                object obj = ResourceManager.GetObject("SortDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortUp {
            get {
                object obj = ResourceManager.GetObject("SortUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a string in a list of strings..
        /// </summary>
        internal static string StringInListDescription {
            get {
                return ResourceManager.GetString("StringInListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a string in a Parameters..
        /// </summary>
        internal static string StringInParametersDescription {
            get {
                return ResourceManager.GetString("StringInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of strings in a Parameters..
        /// </summary>
        internal static string StringListInParametersDescription {
            get {
                return ResourceManager.GetString("StringListInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} value in a Parameters..
        /// </summary>
        internal static string TypeInParametersDescription {
            get {
                return ResourceManager.GetString("TypeInParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} value in a list of {0} values..
        /// </summary>
        internal static string TypeInTypedListDescription {
            get {
                return ResourceManager.GetString("TypeInTypedListDescription", resourceCulture);
            }
        }
    }
}
